### ISSUE TITLE
NotImplementedError:

### ISSUE THREAD

**Issue by Semizenbora** [behzadanksu/rl-attack#1]

**Comment by behzadanksu** [comment]
We noticed this issue just a few days ago. It is probably due to recent architectural updates in both OpenAI Baselines and Cleverhans. We are looking into this and will post an update soon. In the meantime, you can probably run your experiments by reverting to older releases of TF, Baselines, and Cleverhans.

**Comment by Semizenbora** [comment]
Hello, 
How can I revert to the older releases? Thanks in advance

**Comment by behzadanksu** [comment]
@Semizenbora You may. Alternatively, you can use the new release of RL-Attack, which should be compatible with the latest versions of Cleverhans and OpenAI Gym.
